config/routes.rb
CourrierServic3::Application.routes.draw do

  resources :orders
  resources :locations
  resources :users

  get "home/index"

  root :to => "home#index"

  match 'login' => "users#login"
  match 'logout' => "users#logout"

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :order
  attr_accessible :city, :state, :street_1, :street_2, :zip
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :from_loc
  belongs_to :to_loc
  attr_accessible :desc, :package_type, :requested_time, :type, :weight
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :role
  has_many :locations
  ROLES = %w[admin messenger customer]
  validates :email, :format => {
    :with     => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/,
    :message  => "Not a valid email address"
  }
  validates :name, :length => { :minimum => 1, :maximum => 15 }
  validates :password, :length => { :minimum => 6, :maximum => 12 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_current_user
  def load_current_user
    if session[:userid]
      @current_user = User.find(session[:userid])
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @can_edit = params[:id].to_i == session[:userid]

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    if load_user_if_can_edit
    else
      redirect_to :action=>'show'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        @current_user = @user
        session[:userid] = @current_user.id
        format.html { redirect_to @current_user, :notice => 'User was successfully created.' }
        format.json { render :json => @current_user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @current_user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    respond_to do |format|
      if load_user_if_can_edit
        binding.pry
        @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    load_user_if_can_edit
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def login
    @current_user = User.find_by_email(params[:email])
    if @user.nil?         # otherwise take them back to the same page
    else                  # If they logged in correctly
    end
    session[:userid] = @current_user.id
    redirect_to "/"
  end
  def logout
    session[:userid]=false
    @current_user = nil
    redirect_to "/"
  end
  def load_user_if_can_edit
    if session[:userid] == params[:id].to_i
      @user = User.find(session[:userid])
    end
    @can_edit = @user != nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="mantle">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourrierServic3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="cont-<%= controller_name + ' act-' + action_name %>">
  <header>
    <div class="container">
      <h1><a href="/">Courrier Service</a></h1>
      <div>
        <% if session[:userid] %>
          <div class="fleft">
            Welcome <%= link_to(@current_user.name, @current_user) %>
          </div>
          <div class="fright">
            <a href="/logout">Logout</a>
          </div>
        <% else %>
          <div class="fleft">
            <form action="/login" method="POST">
              <div class="fleft">
                <input type="email" name="email" placeholder="Email" />
              </div>
              <div class="fleft">
                <input type="password" name="pass" placeholder="password" />
              </div>
              <div class="fleft">
                <input class="btn" type="submit" value="Login">
              </div>
            </form>
          </div>
          <div class="fright">
            <a href="/users/new">Signup</a>
          </div>
        <% end %>
        <div class="clearfix"></div>
      </div>
      <div class="navbar">
        <nav class="navbar-inner">
          <ul class="nav">
            <li><%= link_to "locations", :controller => "locations", :action => "index" %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div id="main">
    <div class="container">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div class="container">
    </div>
  </footer>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street_1 %>
    <%= f.text_field :street_1 %>
  </div>
  <div class="field">
    <%= f.label :street_2 %>
    <%= f.text_field :street_2 %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_map.html.haml
#location_gMap
%script{ type: "text/javascript", src: "https://maps.googleapis.com/maps/api/js?key=AIzaSyBloH3cURER7UdBL2ie0QL8yOseR7Ypa2w&sensor=true" }
%script{ type: "text/javascript", src:'javascripts/map.js'}

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.street %></td>
    <td><%= location.city %></td>
    <td><%= location.state %></td>
    <td><%= location.zip %></td>
    <td><%= location.user %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>
<div class="fleft">
  <%= render 'form' %>
</div>
<div class="fright">
  <%= render 'map' %>
</div>
<div class="clr"></div>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street:</b>
  <%= @location.street %>
</p>

<p>
  <b>City:</b>
  <%= @location.city %>
</p>

<p>
  <b>State:</b>
  <%= @location.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @location.zip %>
</p>

<p>
  <b>User:</b>
  <%= @location.user %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_loc %><br />
    <%= f.text_field :from_loc %>
  </div>
  <div class="field">
    <%= f.label :to_loc %><br />
    <%= f.text_field :to_loc %>
  </div>
  <div class="field">
    <%= f.label :requested_time %><br />
    <%= f.datetime_select :requested_time %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :package_type %><br />
    <%= f.text_field :package_type %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>From loc</th>
    <th>To loc</th>
    <th>Requested time</th>
    <th>Desc</th>
    <th>Weight</th>
    <th>Package type</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.from_loc %></td>
    <td><%= order.to_loc %></td>
    <td><%= order.requested_time %></td>
    <td><%= order.desc %></td>
    <td><%= order.weight %></td>
    <td><%= order.package_type %></td>
    <td><%= order.type %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From loc:</b>
  <%= @order.from_loc %>
</p>

<p>
  <b>To loc:</b>
  <%= @order.to_loc %>
</p>

<p>
  <b>Requested time:</b>
  <%= @order.requested_time %>
</p>

<p>
  <b>Desc:</b>
  <%= @order.desc %>
</p>

<p>
  <b>Weight:</b>
  <%= @order.weight %>
</p>

<p>
  <b>Package type:</b>
  <%= @order.package_type %>
</p>

<p>
  <b>Type:</b>
  <%= @order.type %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if !@user.id %>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
  <% else %>
    <p>
      <b>Name:</b>
      <%= @user.name %>
    </p>

    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>
  <% end %>
  <div class="field">
    <%= f.label :role %>
    <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>
<p>
  <b>Role:</b>
  <%= @user.role %>
</p>


<% if @can_edit %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', users_path %>